### ISSUE TITLE
allreadability of the entire file

### ISSUE THREAD

**Issue by callmeulas** [t3l3machus/eviltree#2]
X argument of the tool extracts all the given keywords from encrypted SQL files, which is great. However, what we need is to be able to see the whole encrypted file in a readable format. In other words, we don't want to provide a keyword, we want to see the entire file. Is this possible?
![image](https://user-images.githubusercontent.com/96961115/227903360-03944455-0562-46d5-9982-197925426e96.png)

**Comment by t3l3machus** [comment]
@yoap Assuming you don't mean decode/decrypt data as well, I guess you can achieve that using the following regex:  
`-x '[\s\S]*'`
